### ISSUE TITLE
Skill Upgrades - Parent/Children

### ISSUE THREAD

**Issue by Silthus** [raidcraft/rcskills#38]
Es soll die Möglichkeit geben Skills in verschiedenen Upgrade Stufen zu erlangen.
Dabei sollte die nächste Upgrade Stufe nur freischaltbar sein wenn der Skill davor bereits erworben wurde (Parent). Das Upgrade (Child) ersetzt dann den vorherigen Skill und soll den gleichen `alias` verwenden können.

Für Spieler sollten upgrade Skills als ein Skill dargestellt werden die man dann ab einem bestimmten Level upgraden kann. In der Config sollten es aber unterschiedliche Skills sein, da ja es ggf. auch Skills mit unterschiedlichen `types` geben kann. Zum Beispiel der Händler.

```yaml
...
# das sollte die einzig nötige Config Option sein die dann steuert wie die Skills dargestellt werden.
parent: my-base-skill
...
```

**Comment by Silthus** [comment]
Eine andere Idee ist die Upgrades/Childs eines Skills direkt im Skill zu konfigurieren. Das Child ersetzt (deaktiviert) nur den parent wenn `replace-parent: true` gesetzt ist. Der alias, Beschreibung, Name, etc. wird immer von root parent verwendet.

Das Feature könnte man dann sowohl für eine Gruppierung von Skills als auch Upgrades nutzen.

```yaml
type: permission
level: 5
id: 1
...
children:
  # der identifier des sub skills
  foobar:
    # man kann verschiedene types mixen
    type: exp
  blubb:
    # automatisch wird alles des parents übernommen 
    # implizites extends: 1 # id des parents 
    level: 10
    replace-parent: true
    with:
      permissions:
        - Foo
        - bar
```
